{{- if .Values.service.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-wireguard"
  labels:
    app: "{{ .Release.Name }}-wireguard"
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: wg
      protocol: UDP
      port: {{ .Values.service.port }}
      targetPort: 51820
      {{- if .Values.service.type | eq "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- if .Values.service.extraPorts }}
    {{- .Values.service.extraPorts | toYaml | nindent 4 }}
    {{- end }}
  selector:
    app: "{{ .Release.Name }}-wireguard"
    {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.externalIP }}
  externalIPs:
    - {{ .Values.service.externalIP }}
  {{- end }}
{{- end }}